# ANÁLISE DE VENDAS DE ECOMMERCE

## Introdução

Esse projeto vem analisar blablabla despois escrevo isso

## Preparação

In [1]:
# importação das bibliotecas necessárias
import pandas as pd
import sqlite3

In [2]:
#ler o arquivo
df = pd.read_csv('vendas_desafio.csv')

# conferir a integridade dos dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        10000 non-null  int64
 1   data_venda      10000 non-null  str
 2   cliente         10000 non-null  str
 3   produto         10000 non-null  str
 4   categoria       10000 non-null  str
 5   quantidade      10000 non-null  int64
 6   preco_unitario  10000 non-null  float64
 7   vendedor        10000 non-null  str
 8   cidade          10000 non-null  str
 9   estado          10000 non-null  str
dtypes: float64(1), int64(2), str(7)
memory usage: 781.4 KB

In [ ]:
# criar conexão sqlite3
conn = sqlite3.connect('analise_vendas.db')

df.to_sql(
    'vendas', # nome da tabela
    con = conn, # conexão criada acima
    if_exists='replace', # se já existir a tabela, apaga e cria outra
    index=False # não carregar os índices do dataframe na tabela
)

# não esquecer de fechar a conexão
conn.close()

A partir desse ponto já foi criado o banco de dados .db com os dados do .csv original. Assim, já é possível usar comando SQL para iniciar as atividades propostas.

In [4]:
df.head()

,id_venda,data_venda,cliente,produto,categoria,quantidade,preco_unitario,vendedor,cidade,estado
0,1,2024-09-27,Pietra,Mouse,Eletrônicos,3,84.74,Ana,Belo Horizonte,RJ
1,2,2024-01-21,Vinicius,Monitor,Eletrônicos,3,950.34,Bruno,São Paulo,RS
2,3,2024-08-02,Yago,Mouse,Eletrônicos,3,79.13,Eduardo,Curitiba,SP
3,4,2024-04-09,Lara,Notebook,Eletrônicos,3,3471.47,Ana,Rio de Janeiro,RJ
4,5,2024-05-29,Levi,Fone,Eletrônicos,4,208.32,Eduardo,São Paulo,RS

## Atividades em SQL

### 1. Qual o faturamento total por produto?

In [33]:
# abre a conexão com o banco de dados
conn = sqlite3.connect("analise_vendas.db")

# a query a ser executada
query = """ 
    SELECT
        produto,
        'R$ ' || format('%,.2f', SUM(quantidade * preco_unitario)) AS faturamento_total
    FROM vendas 
    GROUP BY produto
    ORDER BY SUM(quantidade * preco_unitario) DESC
"""

# execução da query criada acima
df = pd.read_sql_query(query, con=conn)

# não esquecer de fechar a conexão
conn.close()

# exibir o df
df

        produto faturamento_total
0      Notebook   R$ 8,290,852.39
1          Mesa   R$ 3,092,939.21
2       Monitor   R$ 2,364,641.86
3       Cadeira   R$ 1,629,832.30
4          Fone     R$ 495,633.09
5       Mochila     R$ 460,376.91
6       Teclado     R$ 384,771.59
7  Livro Python     R$ 296,630.22
8     Livro SQL     R$ 247,460.70
9         Mouse     R$ 205,764.16

_nota:_ A concatenação de 'R$' e o uso de _format_ são apenas para facilitar a visualização do resultado. O número em si continua como um float.

### 2. Qual o faturamento total por categoria?

### 3. Qual o ticket médio por cliente?

### 4. Qual o faturamento total por vendedor?

### 5. Qual o faturamento por mês?

### 6. Quais são os 5 produtos mais vendidos?

### 7. Qual cidade possui maior faturamento?

### 8. Qual cliente comprou mais em valor?